# Generated by Django 3.1.13 on 2022-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_auto_20220214_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
